article/urls.py
from django.conf.urls import url
from . import views, list_views

app_name = 'article'
urlpatterns = [
    url(r'^article-column/$', views.article_column, name="article_column"),
    url(r'^rename-column/$', views.rename_article_column, name='rename_article_column'),
    url(r'^del-column/$', views.del_article_column, name="del_article_column"),
    url(r'^article-post/$', views.article_post, name="article_post"),
    url(r'^article-list/$', views.article_list, name="article_list"),
    url(r'^article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),
    url(r'^del-article/$', views.del_article, name="del_article"),
    url(r'^edit-article/(?P<article_id>\d+)/$', views.edit_article, name="edit_article"),
    url(r'^list-article-titles/$', list_views.article_titles, name="article_titles"),
    url(r'^list-article-detail/(<?P<id>\d+)/(?P<slug>[-\w]+)/$',list_views.article_detail,name="list_article_detail"),

]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url

urlpatterns = [
	url(r'^blog/',include('tblog.urls',namespace="blog")),
    path('admin/', admin.site.urls),
    url(r'^account/',include('account.urls',namespace="account")),
    url(r'^article/', include('article.urls', namespace='article'))
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from slugify import slugify
from django.urls import reverse
# Create your models here.
class ArticleColumn(models.Model):
    user = models.ForeignKey(User, related_name='article_column', on_delete=models.CASCADE)
    column = models.CharField(max_length=30)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.column

class ArticlePost(models.Model):
    author = models.ForeignKey(User, related_name="article", on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)
    column = models.ForeignKey(ArticleColumn, related_name="article_column", on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('title',)
        index_together = (('id','slug'),)

    def __str__(self):
        return self.title

    def save(self, *args, **karges):
        self.slug = slugify(self.title)
        super(ArticlePost, self).save(*args, **karges)

    def get_absolute_url(self):
        return reverse("article:article_detail", args=[self.id, self.slug])

    def get_url_path(self):
        return reverse('article:list_article_detail', args=[self.id, self.slug])

article/forms.py
from django import forms
from .models import ArticleColumn,ArticlePost

class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ('column',)

class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ('title','body')

article/views.py
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from .models import ArticleColumn,ArticlePost
from django.http import HttpResponse
from .forms import ArticleColumnForm,ArticlePostForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.

@login_required(login_url='/account/login/')
@csrf_exempt
def article_column(request):
    if request.method == "GET":
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        return render(request, 'article/column/article_column.html', {'columns':columns, 'column_form':column_form})

    if request.method =="POST":
        column_name = request.POST['colunm']
        columns = ArticleColumn.objects.filter(user_id = request.user.id, column = column_name)
        if columns:
            return HttpResponse(2)
        else:
            ArticleColumn.objects.create(user = request.user, column=column_name)
            return HttpResponse(1)
@login_required(login_url='/account/login/')
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST['column_name']
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.column = column_name
        line.save()
        return HttpResponse(1)
    except:
        return HttpResponse(0)

@login_required(login_url='/account/login/')
@csrf_exempt
def del_article_column(request):
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id = column_id)
        line.delete()
        return HttpResponse(1)
    except:
        return HttpResponse(2)
#添加文章
@login_required(login_url='/account/login/')
@csrf_exempt
def article_post(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd =article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                return HttpResponse(1)
            except:
                return HttpResponse(2)

        else:
            return HttpResponse(3)
    else:
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()

        return render(request, 'article/column/article_post.html', {"article_post_form":article_post_form, "article_columns":article_columns})

# 文章列表
@login_required(login_url='/account/login/')
def article_list(request):
    articles = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(articles,2)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    return render(request, 'article/column/article_list.html', {"articles":articles, 'page':current_page})

@login_required(login_url="/account/login")
def article_detail(request, id, slug):
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    return render(request, 'article/column/article_detail.html', {'article':article})

@login_required(login_url='/account/login')
@csrf_exempt
def del_article(request):
    article_id = request.POST['article_id']

    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse('1')
    except:
        return HttpResponse('2')

@login_required(login_url="/account/login/")
@csrf_exempt
def edit_article(request, article_id):
    if request.method == "GET":
        article_columns = request.user.article_column.all()
        article = ArticlePost.objects.get(id=article_id)
        this_article_form = ArticlePostForm(initial={'title':article.title})
        this_article_column = article.column
        return render(request, 'article/column/edit_article.html', {'article':article, "article_columns":article_columns, 'this_article_form':this_article_form,
                                                                    "this_article_column":this_article_column})
    else:
        edit_article = ArticlePost.objects.get(id=article_id)
        try:
            edit_article.column = request.user.article_column.get(id=request.POST['column_id'])
            edit_article.title = request.POST['title']
            edit_article.body = request.POST['body']
            edit_article.save()
            return HttpResponse('1')
        except:
            return HttpResponse('2')

templates/article/column/article_column.html
{% extends 'article/base.html' %}
{% load staticfiles %}
{% block title %}article column{% endblock %}
{% block content %}
    <div>
        <p class="text-right"><button class="btn btn-primary" id="add_column" onclick="add_column()">add column</button> </p>
        <table class="table table-hover">
            <tr>
                <td>序号</td>
                <td>栏目名称</td>
                <td>操作</td>
            </tr>
            {% for column in columns %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ column.column }}</td>
                    <td>
                        <a href="javascript:void(0)" name="eidt" onclick="edit_column(this,{{ column.id }})"><span class="glyphicon glyphicon-pencil"></span> </a>
                        <a href="javascript:void(0)" name="delete" onclick="del_column(this,{{ column.id }})"><span class="glyphicon glyphicon-trash"></span> </a>
                    </td>
                </tr>
                {% empty %}
                <p>还没有设置栏目，太懒了</p>
            {% endfor %}
        </table>
    </div>
    <script type="text/javascript" src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
    <script type="text/javascript">
        function add_column() {
            var index = layer.open({
                type:1,
                skin:"layui-layer-rim",
                area:["400px","200px"],
                title:'新增栏目',
                content:"<div class='text-center' style='margin-top:20px'><p>请输入新的栏目名称</p><p><input type='text' id='id_column'></p></div>",
                btn:['确定','取消'],
                yes:function(index, layero){
                    column_name = $('#id_column').val();
                    $.ajax({
                        url:'{% url "article:article_column" %}',
                        type:"POST",
                        data:{"colunm":column_name},
                        success:function(e){
                            if(e == 1){
                                layer.msg('good')
                                parent.location.reload()
                            }else{
                                layer.msg('此栏目已有，请更换名称')
                            }
                        }
                    });
                },
                btn2:function(index, layero){
                    layer.close(index);
                }
            });
        }

        function edit_column(ele, column_id){
            var name = $(ele).parents('tr').children("td").eq(1).text();
            var index = layer.open({
                type:1,
                skin:"layui-layer-rim",
                area:["400px","200px"],
                title:"编辑栏目",
                content:'<div class="text-center" style="margin-top:20px"><p>请编辑栏目名称</p><p><input type="text" id="new_name" value="'+name+'"></p></div>',
                btn:['确定','取消'],
                yes:function(index, layero){
                    new_name = $('#new_name').val();
                    $.ajax({
                        url:'{% url 'article:rename_article_column' %}',
                        type:"POST",
                        data:{"column_id":column_id,"column_name":new_name},
                        success: function(e){
                            if (e == 1) {
                                parent.location.reload();
                                layer.msg('修改成功');
                            } else {
                                layer.msg('修改失败！');
                            }
                        }
                    });
                }
            });
        }

        function del_column(ele,column_id) {
            var name = $(ele).parents('tr').children('td').eq(1).text()
            layer.open({
                type:1,
                skin:"layui-layer-rim",
                area:['400px','200px'],
                title:'删除栏目',
                content:'<div class="text-center" style="margin-top:20px"><p>是否确定删除{'+name+'}栏目</p></div>',
                btn:['确定','取消'],
                yes:function () {
                    $.ajax({
                        url:'{% url 'article:del_article_column' %}',
                        type:"POST",
                        data:{"column_id":column_id},
                        success:function(e){
                            if(e==1){
                                parent.location.reload();
                                layer.msg('成功删除');
                            }else{
                                layer.msg('删除失败！');
                            }
                        }
                    });
                }
            });
        }
    </script>
{% endblock %}

templates/article/column/article_detail.html
{% extends 'article/base.html' %}
{% load staticfiles %}
{% block title %}artilce detail {% endblock %}
{% block content %}
    <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.min.css' %}" />
    <div >
        <h1>{{ article.title }}</h1>
        <p>{{ user.username }}</p>
        <div id="editormd-view">
            <textarea id="append-test" style="display:none;">
{{ article.body }}
            </textarea>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
    <script src="{% static 'editor/lib/marked.min.js' %}"></script>
    <script src="{% static 'editor/lib/prettify.min.js' %}"></script>
    <script src="{% static 'editor/lib/raphael.min.js' %}"></script>
    <script src="{% static 'editor/lib/underscore.min.js' %}"></script>
    <script src="{% static 'editor/lib/sequence-diagram.min.js' %}" ></script>
    <script src="{% static 'editor/lib/flowchart.min.js' %}" ></script>
    <script src="{% static 'editor/lib/jquery.flowchart.min.js' %}" ></script>
    <script src="{% static 'editor/editormd.min.js' %}"></script>
    <script>
        $(function () {
            editormd.markdownToHTML("editormd-view", {
                htmlDecode : "style,script,iframe",
                emoji : true,
                taskList : true,
                tex : true,
                flowChart : true,
                sequenceDiagram : true,
            });
        });
    </script>
{% endblock %}

templates/article/column/article_list.html
{% extends 'article/base.html' %}
{% load staticfiles %}
{% block title %} articles list {% endblock %}

{% block content %}
    <div >
        <table class="table table-hover">
            <tr>
                <td>序号</td>
                <td>标题</td>
                <td>栏目</td>
                <td>操作</td>
            </tr>
            {% for article in articles %}
                <tr id="{{ article.id }}">
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{{ article.get_absolute_url }}" >{{ article.title }}</a></td>
                    <td>{{ article.column }}</td>
                    <td><a href="{% url 'article:edit_article' article.id %}"><span class="glyphicon glyphicon-pencil"></span></a> <a href="javascript:void(0)" onclick="del_article(this, {{ article.id }})"><span class="glyphicon glyphicon-trash"></span></a> </td>
                </tr>
            {% endfor %}

        </table>
        {% include 'paginator.html' %}
    </div>
    <script type="text/javascript" src="{% static 'js/jquery-1.11.1.min.js' %}" ></script>
    <script type="text/javascript" src="{% static 'js/layer.js' %}" ></script>
    <script>
        function del_article(ele, article_id) {
            var article_name = $(ele).parents("tr").children('td').eq(1).text();
            layer.open({
                type: 1,
                skin: "layui-layer-rim",
                area: ['400px', '200px'],
                title: '删除文章',
                content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除《'+article_name+'》</p></div>',
                btn: ['确定', '取消'],
                yes: function() {
                    $.ajax({
                        type: "POST",
                        url: "{% url "article:del_article" %}",
                        data: {article_id:article_id},
                        success:function(e) {
                            if (e == 1) {
                                layer.msg("delete success!");
                                parent.location.reload();
                            } else {
                                layer.msg('删除失败！');
                            }
                        }
                    });
                }
            });
        }
    </script>
{% endblock %}

templates/article/column/article_post.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}article post {% endblock %}
{% block content %}
    <link rel="stylesheet" href="{% static 'editor/css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}" />
    <div style="margin-left: 10px;">
        <form class="form-horizontal" action="." method="post">{% csrf_token %}
            <div class="row" style="margin-top: 10px;">
                <div class="col-md-2 text-right"><span>标题：</span></div>
                <div class="col-md-10 text-left">{{ article_post_form.title }}</div>
            </div>
            <div class="row" style="margin-top: 10px">
                <div class="col-md-2 text-right"><span>栏目：</span></div>
                <div class="col-md-10 text-left">
                    <select id="which_column">
                        {% for column in article_columns %}
                            <option value="{{ column.id }}">{{ column.column }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="row" style="margin-top:10px">
                <div class="col-md-2 text-right"><span>内容：</span></div>
                <div id="editormd" class="col-md-10 text-left">
                    <textarea style="display: none;" id="id_body" ></textarea>
                </div>
            </div>
            <div class="row">
                <input type="button" class="btn btn-primary btn-lg" value="发布"  onclick="public_article()"/>
            </div>
        </form>
    </div>
    <script type="text/javascript" src="{% static "js/jquery-1.11.1.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/layer.js" %}" ></script>
    <script type="text/javascript" src="{% static 'editor/editormd.amd.min.js' %}" ></script>
    <script type="text/javascript">
        function  public_article() {
            var title = $('#id_title').val();
            var column_id = $('#which_column').val();
            var body = $('#id_body').val();
            $.ajax({
                type:'POST',
                url:"{% url 'article:article_post' %}",
                data:{title:title, body:body, column_id:column_id},
                success:function (e) {
                    if (e == 1) {
                        layer.msg('successful');
                        window.location.href =  "{% url 'article:article_list' %}";
                    } else {

                        layer.msg('保存失败！');
                    }

                }
            });
        }

        $(function(){
            var editor = editormd("editormd", {
                width : "100%",
                height : "640",
                syncScorlling : "single",
                path : "{% static 'editor/lib/' %}",
            });
        })
    </script>
{% endblock %}

templates/article/column/edit_article.html
{% extends 'article/base.html' %}
{% load staticfiles %}
{% block title %}edit article{% endblock %}
{% block content %}
    <link rel="stylesheet" href="{% static 'editor/css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'editor/css/editormd.min.css' %}" />
    <div class="container">

        <div class=" col-md-10">
            <div style="margin-left: 10px;">
                <form class="form-horizontal" action="." method="post">{% csrf_token %}
                    <div class="row" style="margin-top: 10px;">
                        <div class="col-md-2 text-right"><span>标题：</span></div>
                        <div class="col-md-10 text-left">{{ this_article_form.title }}</div>
                    </div>
                    <div class="row" style="margin-top: 10px">
                        <div class="col-md-2 text-right"><span>栏目：</span></div>
                        <div class="col-md-10 text-left">
                            <select id="which_column">
                                {% for column in article_columns %}
                                    <option value="{{ column.id }}">{{ column.column }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="row" style="margin-top: 10px;">
                        <div class="col-md-2 text-right"><span>内容：</span></div>
                        <div id="editormd" class="col-md-10 text-left">
                            <textarea style="display:none;" id="id_body" >{{ article.body }}</textarea>
                        </div>
                    </div>
                    <div class="row">
                        <input type="button" class="btn btn-primary btn-lg" value="发布" onclick="edit_article()"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
    <script type="text/javascript" src="{% static 'editor/editormd.min.js' %}"></script>
    <script>
        $(function () {
           var editor = editormd("editormd", {
              width : "100%",
              height: '640px',
              path : "{% static 'editor/lib/' %}",
           });
        });

        function edit_article() {
            var title = $('#id_title').val();
            var column_id = $('#which_column').val();
            var body = $('#id_body').val();
            $.ajax({
                type:"POST",
                url:"{% url 'article:edit_article' article.id %}",
                data:{title:title, column_id:column_id, body:body},
                success:function (e) {
                    if (e == '1') {
                        layer.msg('successful');
                        location.href = "{% url 'article:article_list' %}";
                    } else {
                        layer.msg('sorry');
                    }
                }
            });
        }
    </script>
{% endblock %}