account/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import  views as auth_views
from django.conf import settings
app_name='account'
urlpatterns=[
    # url(r'^login/$',views.user_login,name="user_login")
    url(r'^login/$', auth_views.login,{'template_name':'account/login.html'}, name="user_login"),
    url(r'^logout/$',auth_views.logout,{'template_name':'account/logout.html'}, name="user_logout"),
    url(r'^register/$',views.register, name="user_register"),
    url(r'^password-change/$', auth_views.password_change, {'post_change_redirect':'/account/password-change-done'}, name='password_change'),
    url(r'^password-change-done/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^password-reset/$', auth_views.password_reset, {"template_name":'account/password_reset_form.html','email_template_name':'account/password_reset_email.html',
                                                        'subject_template_name':'account/password_reset_subject.txt','post_reset_redirect':'/account/password-reset-done'},
        name="password_reset"),
    url(r'^password-reset-done/$',auth_views.password_reset_done,{"template_name":'account/password_reset_done.html'}, name="password_reset_done"),
    url(r"^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$", auth_views.password_reset_confirm, {"template_name":'account/password_reset_confirm.html',
                                                                                                             'post_reset_redirect':'/account/password-reset-complete'},
        name="password_reset_confirm"),
    url(r"^password-reset-complete/$", auth_views.password_reset_complete, {"template_name":"account/password_reset_complete.html"}, name="password_reset_complete"),
    url(r"^my-information/$", views.myself, name="my_information"),
    url(r"^edit-my-information/$", views.myself_edit, name="edit_my_information"),
    url(r"^my-image/$", views.my_image, name="my_image")
]

article/urls.py
from django.conf.urls import url
from . import views, list_views

app_name = 'article'
urlpatterns = [
    url(r'^article-column/$', views.article_column, name="article_column"),
    url(r'^rename-column/$', views.rename_article_column, name='rename_article_column'),
    url(r'^del-column/$', views.del_article_column, name="del_article_column"),
    url(r'^article-post/$', views.article_post, name="article_post"),
    url(r'^article-list/$', views.article_list, name="article_list"),
    url(r'^article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),
    url(r'^del-article/$', views.del_article, name="del_article"),
    url(r'^edit-article/(?P<article_id>\d+)/$', views.edit_article, name="edit_article"),
    url(r'^list-article-titles/$', list_views.article_titles, name="article_titles"),
    url(r'^list-article-detail/(<?P<id>\d+)/(?P<slug>[-\w]+)/$',list_views.article_detail,name="list_article_detail"),

]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url

urlpatterns = [
	url(r'^blog/',include('tblog.urls',namespace="blog")),
    path('admin/', admin.site.urls),
    url(r'^account/',include('account.urls',namespace="account")),
    url(r'^article/', include('article.urls', namespace='article'))
]

tblog/urls.py
from django.conf.urls import url
from . import views
app_name="blog"
urlpatterns=[
	url(r'^$',views.blog_title,name="blog_title"),
	url(r'(?P<article_id>\d)/$',views.blog_article,name="blog_detail"),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
</head>
<body>
    {% include "header.html" %}
	<div class="container">
		{% block content %}
			
		{% endblock %}
	</div>
    {% include "footer.html" %}
	{% block javascript %}
    {% endblock %}
</body>
</html>

templates/footer.html
<div class="container">
    <hr/>
    <p class="text-center">copy right hk.ooing.cn</p>
</div>

templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://hk.ooing.cn">
                <img src="{% static 'images/logo.jpg' %}" width="20px"/>
            </a>
        </div>
        <div>
            <ul class="nav navbar-nav" >
                <li><a href="{% url 'blog:blog_title' %}">BLOG</a> </li>
                <li><a href="{% url 'article:article_titles' %}">文章</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right:10px;">
                {% if user.is_authenticated %}
                    <li>
                    <div class="dropdown" style="margin-top: 8px;">
                        <button clas="btn btn-default dropdown-toggle" type="button" id="dropdownMenu" data-toggle="dropdown">{{ user.username }}
                            <span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'account:password_change' %}">修改密码</a> </li>
                            <li><a href="{% url 'account:my_information' %}">个人信息</a> </li>
                            <li><a href="{% url 'account:user_logout' %}">Logout</a> </li>
                        </ul>
                    </div>
                    </li>
                {% else %}
                    <li><a href="{% url 'account:user_login' %}">LOGIN</a> </li>
                    <li><a href="{% url 'account:user_register' %}">Sign up</a> </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

templates/paginator.html
<div class="pagination">
    <span class="step-links" >
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
    <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}
    </span>
    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
    </span>
</div>